apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management
  labels:
    app: task-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
      - name: task-management
        image: task-management:latest
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "0"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: task-management-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: task-management-secrets
              key: secret-key
        - name: ALLOWED_HOSTS
          value: "task-management.example.com"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20 